apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    app: qdr
spec:
  ports:
  - port: 5672
    name: amqp
  - port: 5671
    name: amqps
  - port: 55672
    name: inter-router
  selector:
    type: router
---
apiVersion: v1
kind: Service
metadata:
  name: router-agent
  labels:
    app: qdr
spec:
  ports:
  - port: 55672
    name: amqp
  selector:
    type: router-agent
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qdr
        version: v1
        type: router
    spec:
      containers:
      - name: qdr
        image: gordons/qdr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
          protocol: TCP
        volumeMounts:
        - name: qdr-config
          mountPath: /etc/qpid-dispatch
        - name: qdr-cert
          readOnly: true
          mountPath: /etc/qpid-dispatch-certs/
      volumes:
      - name: qdr-config
        configMap:
          name: qdr-config
      - name: qdr-cert
        secret:
          secretName: qdr-cert
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdr-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qdr
        version: v1
        type: router-agent
    spec:
      containers:
      - name: qdr-agent
        image: gordons/qda:latest
        imagePullPolicy: IfNotPresent
        command:
        - node
        - /opt/app-root/src/bin/ragent.js
        ports:
        - containerPort: 55672
          protocol: TCP
