apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    app: qdr
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: qdr-external-cert
spec:
  ports:
  - port: 5672
    name: amqp
  - port: 5671
    name: amqps
  - port: 8080
    name: http
  - port: 55672
    name: inter-router
  selector:
    type: qdrouterd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qdr
        version: v1
        type: qdrouterd
    spec:
      containers:
      - name: qdr
        image: gordons/qdr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
          protocol: TCP
        volumeMounts:
        - name: qdr-config
          mountPath: /etc/qpid-dispatch
        - name: external-certs
          readOnly: true
          mountPath: /etc/qpid-dispatch-certs/external
        - name: internal-certs
          readOnly: true
          mountPath: /etc/qpid-dispatch-certs/internal
      volumes:
      - name: qdr-config
        configMap:
          name: qdr-config
      - name: external-certs
        secret:
          secretName: qdr-external-cert
      - name: internal-certs
        secret:
          secretName: qdr-internal-cert
---
apiVersion: v1
kind: Route
metadata:
  name: router-console
spec:
  host: router-console-cluster-local.192.168.1.90.nip.io
  to:
    kind: Service
    name: messaging
  port:
    targetPort: 8080
